name: CI NestJs

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs: 
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Testing Start
              run: echo Hello World!
            - name: Repository checkout
              uses: actions/checkout@v4
            - name: Setup Node.js Environment
              uses: actions/setup-node@v4
              with:
                node-version: 'latest'
            - name: Install Npm Packages
              run: npm install
            - name: Run Testing
              run: npm run test
