name: NEST CI Release

on:
    pull_request:
      types: [opened, synchronize, reopened]
      branches:
        - release/*
    workflow_dispatch:
    push:
      branches:
        - release/*

concurrency:
  group: ${{github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    common_jobs:
        uses: ./.github/workflows/common_jobs.yml
    docker-build: 
        runs-on: ubuntu-latest
        needs:
          - common_jobs
        steps: 
          - name: Repository Checkout
            uses: actions/checkout@v4
          
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
          
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

          - name: Build Docker Image
            run: docker build --platform linux/amd64 -t nest-devops:latest . --load

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Push Docker image to Docker Hub
            run: |
                docker tag nest-devops ${{ secrets.DOCKERHUB_USERNAME }}/nest-devops:latest
                docker push ${{ secrets.DOCKERHUB_USERNAME }}/nest-devops:latest